### Title: Categorising how the clonal and sub-clonal stages contribute to the overall mutational siganture profile
## Author: Sander Vlugter
## Date (final version): 18/May/2020
## Description:
## Here we use the fit_to_signature data of the clonal, sub-clonal stages and the combined/overall mutational signature profiles
## to categorise how and to what degree the 2 stages contribute to the overall mutational signature profiles of the samples.
## Using the data generated by: "Low_cosine_clonal_subclonal_stages.R".
######
library(MutationalPatterns)
#### load the required data:
hmf_meta_pure<- readRDS("~/path/to/hmfdata/hmf_meta_pure.RDS")
fitted_clonal<-readRDS("~/path/to/fitted_sig/clonal_fitted.RDS")
fitted_combined<-readRDS("~/path/to/fitted_sig/combined_fitted.RDS")
fitted_subclonal<-readRDS("~/path/to/fitted_sig/subclonal_fitted.RDS")
## load the COSMIC mutational signatures from MutationalPatterns
cosmic_signatures <- readRDS(system.file("states/COSMIC_signatures.rds",
                                         package = "MutationalPatterns"))
## remove signatures known to be caused by sequencing artefacts
cosmic_signatures$snv =cosmic_signatures$snv[,-c(32,48,50:65)]
## calculate the cosine similarity of the fitted stages 
cosine_sig_clonal_subclonal <- diag(cos_sim_matrix(fitted_clonal$contribution, fitted_subclonal$contribution))
cosine_sig_combined_clonal <- diag(cos_sim_matrix(fitted_combined$contribution, fitted_clonal$contribution))
cosine_sig_combined_subclonal <- diag(cos_sim_matrix(fitted_combined$contribution, fitted_subclonal$contribution))
## put them together in a dataframe
cosine_sig_profiles<- cbind(cosine_sig_combined_clonal, cosine_sig_combined_subclonal,cosine_sig_clonal_subclonal)
cosine_sig_profiles <- as.data.frame(cosine_sig_profiles)
########## The different categories ###########
### Definitions of the categories used:
#### Category A) Samples where the mutational signature profiles of the clonal and sub-clonal stage are highly similar,
## meaning that they show the same mutational signatures in both stages. cosine sim threshold:
## cosine similarity between clonal and sub-clonal >=0.8. 
#### Category B) Samples where the mutational signature profile of the clonal stage best resembles (is highly similar),
## to the overall mutational signature profile of the sample. Cosine sim threshold:
## cosine similarity between clonal and overall > cosine similarity between sub-clonal and overall &
## cosine similarity between clonal and sub-clonal stage <0.8.
#### Category C) Samples where the mutational signature profile of the sub-clonal stage best resembles (is highly similar),
## to the overall mutational signature profile of the sample. Cosine sim threshold:
## cosine similarity between sub-clonal and overall > cosine similarity between clonal and overall &
## cosine similarity between clonal and sub-clonal stage <0.8.
#### Category D) Samples where neither the clonal or sub-clonal stage is highly similar to the overall mutational signature
## profile. Meaning the overall mutational signature profile is based on equall contribution of both stages,
## but the mutational signature profiles of the stages have a low cosine similarity between them.
## cosine sim threshold: cosine sim between clonal and combined <0.8 & cosine sim between sub-clonal and combined <0.8
## & cosine sim between clonal and sub-clonal <0.8.
######### Subsetting the samples belonging to the defined Categories ########
######## select samples belonging to Category A:
Id_same_signatures<- rownames(cosine_sig_profiles)[which(cosine_sig_profiles$cosine_sig_clonal_subclonal >=0.8)]
######## select samples belonging to Category B:
Id_clo_lead_signatures <- rownames(cosine_sig_profiles)[which(cosine_sig_profiles$cosine_sig_combined_clonal > cosine_sig_profiles$cosine_sig_combined_subclonal &
                                                                cosine_sig_profiles$cosine_sig_clonal_subclonal <0.8)]
######## select samples belonging to Category C:
Id_sub_lead_signatures <-rownames(cosine_sig_profiles)[which(cosine_sig_profiles$cosine_sig_combined_clonal < cosine_sig_profiles$cosine_sig_combined_subclonal &
                                                               cosine_sig_profiles$cosine_sig_clonal_subclonal<0.8)]
######## select samples belonging to Category D:
Id_combined_lead_signaturees <- rownames(cosine_sig_profiles)[which(cosine_sig_profiles$cosine_sig_combined_clonal <0.8 &
                                                                      cosine_sig_profiles$cosine_sig_combined_subclonal<0.8 &
                                                                      cosine_sig_profiles$cosine_sig_clonal_subclonal<0.8)]
### remove samples that are called dubble over multiple categories
Id_sub_lead_signatures<- Id_sub_lead_signatures[!Id_sub_lead_signatures %in% Id_combined_lead_signaturees]
Id_clo_lead_signatures<- Id_clo_lead_signatures[!Id_clo_lead_signatures %in% Id_combined_lead_signaturees]
## check to see if all samples are categorised, and none are categorised twice
length(c(Id_same_signatures,Id_clo_lead_signatures,Id_combined_lead_signaturees,Id_sub_lead_signatures))
length(unique(c(Id_same_signatures,Id_clo_lead_signatures,Id_combined_lead_signaturees,Id_sub_lead_signatures)))
## create dataframe of the categories:
Category_distribution<- data.frame("Categories"=c("Category A","Category B","Category C","Category D"),
           "Number_of_samples"=c(length(Id_same_signatures),
                                 length(Id_clo_lead_signatures),
                                 length(Id_sub_lead_signatures),
                                 length(Id_combined_lead_signaturees)))

##### Additional analyses, not for figures but to analyse the raw mutation counts ####
#### alter the object names to obtain information on the raw mutation counts of the samples stages
CatA <- as.vector(Id_same_signatures)
CatB <- as.vector(Id_clo_lead_signatures)
CatC <- as.vector(Id_sub_lead_signatures)
CatD <- as.vector(Id_combined_lead_signaturees)

### add them to a list
Categories <- list("A"=CatA,
                   "B"=CatB,
                   "C"=CatC,
                   "D"=CatD)

## open the raw mutation count data for the samples stages
subclonal <-readRDS("~/path/to/hmfdata/subclonal.RDS")
clonal <-readRDS("~/path/to/hmfdata/clonal.RDS")
combined<- readRDS("~/path/to/hmfdata/combined.RDS")
## returns the how many more mutations there are in the clonal stage of the sample
for(x in Categories){
   tmp_clonal<-colSums(clonal[,x])
   tmp_subclonal <- colSums(subclonal[,x])
   tmp_comp<-cbind(tmp_clonal,tmp_subclonal)
   tmp_more_clonal<- tmp_comp[,1]-tmp_comp[,2]
   print(tmp_more_clonal)
}
### analyse the samples of CatD further based on metadata entries
hmf_meta_pure[match(CatD,hmf_meta_pure$sampleId),]
### create contribution plots of mutational signatures for both stages
## be aware the colors in the legends are different in the plots 
CatD_clo_contri <- plot_contribution(fitted_clonal$contribution[,CatD],cosmic_signatures,type = "snv",mode = "relative")
CatD_sub_contri <- plot_contribution(fitted_subclonal$contribution[,CatD],cosmic_signatures,type = "snv",mode = "relative")
CatD_com_contri <- plot_contribution(fitted_combined$contribution[,CatD],cosmic_signatures,type = "snv",mode = "relative")
